[#13] Create a manager registry in order to get access to all managers
socon-dev/socon pull request #23
Opened 2023-05-05 20:42 UTC by StephaneCapponi

2023-05-09 07:33 UTC, StephaneCapponi commented
@JRbemt, could you check that pull request ?

2023-05-10 12:23 UTC, JRbemt requested changes
Looks good, some references to BaseManager should be updated in the docs. But the code looks fine

2023-05-10 12:23 UTC, JRbemt commented on docs/how-to/custom-managers-and-hooks.txt
One ref to :class:`~socon.core.manager.BaseManager._managers`

2023-05-10 12:23 UTC, JRbemt commented on docs/intro/tutorials/3_manager.txt
:class:`~socon.core.manager.BaseManager` outdated reference on line 182

2023-05-10 12:23 UTC, JRbemt commented on docs/ref/manager.txt
> +
At the start Socon creates a ``managers`` object that is accessible like this::

2023-05-10 12:23 UTC, JRbemt commented on socon/core/manager.py
> +    """Base class that register all managers"""
```suggestion
    """Base class that registers all managers"""
```

2023-05-10 12:23 UTC, JRbemt commented on socon/core/manager.py
> +    """Base class that register all managers"""
```suggestion
    """Base class that registers all managers"""
```

2023-05-11 15:19 UTC, JRbemt approved these changes

2023-05-11 15:23 UTC, merged